name: template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

  # design
  google_fonts: ^6.3.2
  easy_localization: ^3.0.8

  # State
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Firebase
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  firebase_auth: ^6.1.1
  firebase_analytics: ^12.0.3
  cloud_firestore: ^6.0.3

  # Screen
  flutter_screenutil: ^5.9.3
  loader_overlay: ^5.0.0
  flutter_native_splash: ^2.4.7

  # Social Login
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # Common
  shared_preferences: ^2.5.3
  go_router: ^16.3.0
  fluttertoast: ^9.0.0

  # Model
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Data
  equatable: ^2.0.7

  pedantic_mono: ^1.34.0
  http: ^1.5.0
  global_configuration: ^2.0.0
  table_calendar: ^3.2.0
  calendar_view: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # build
  build_runner: ^2.7.1

  # Model
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  # State
  riverpod_generator: ^3.0.3

  # Log
  logger: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
